name: Christopher Clark
favicon: null
layout_spectrum: 0.24021
typography_spectrum: 0.71269
title: Official site of fantasy author Christopher Clark
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a3f49'
    - '#4e5255'
    - '#fefefe'
    - '#5a7c83'
    - '#b2c1c5'
  brandStrength: 0.8125
  lightness: 0.625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
