name: Christopher Clark
favicon: null
layout_spectrum: 0.71432
typography_spectrum: 0.71269
title: Official site of fantasy author Christopher Clark
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a3f49'
    - '#4e5255'
    - '#fefefe'
    - '#5a7c83'
    - '#b2c1c5'
  brandStrength: 0.125
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
