name: Christopher Clark
favicon: null
layout_spectrum: 0.13693
typography_spectrum: 0.70056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a3f49'
    - '#4e5255'
    - '#fefefe'
    - '#5a7c83'
    - '#b2c1c5'
  brandStrength: 0.09092897130176425
  lightness: 0.6821581439580768
  saturation: 0.08430784055963159
  rhythmicContrast: 0.20339964097365737
purpose: []
